<?php
/**
 * GENERATED by tools/import-food.php from the app's lib/seed/food.json. Do not edit by hand:
 * fix the text in the app seed and re-run the import.
 * updated: date of the import. foods: slug => {name,synonyms[],verdict:safe|precaucion|evitar,reason,detail:?string,source,
 * reviewedBy:?string,published:bool (reviewed),page:bool (published AND has detail)}.
 */
declare(strict_types=1);

return array (
  'preview' => false,
  'updated' => '2026-09-27',
  'foods' => 
  array (
    'achuras' => 
    array (
      'name' => 'Achuras y mondongo',
      'synonyms' => 
      array (
        0 => 'chinchulines',
        1 => 'mondongo',
        2 => 'riñones',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Cociná siempre bien las achuras por dentro y no las comas muy seguido: son altas en grasa y colesterol.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'agua-de-coco' => 
    array (
      'name' => 'Agua de coco',
      'synonyms' => 
      array (
        0 => 'coco frío',
      ),
      'verdict' => 'safe',
      'reason' => 'Es una bebida natural e hidratante, buena opción con el calor.',
      'detail' => NULL,
      'source' => 'Mayo Clinic — Pregnancy nutrition',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'alcohol' => 
    array (
      'name' => 'Alcohol (cualquier bebida alcohólica)',
      'synonyms' => 
      array (
        0 => 'cerveza',
        1 => 'vino',
        2 => 'caña',
        3 => 'whisky',
        4 => 'tereré con caña',
      ),
      'verdict' => 'evitar',
      'reason' => 'No se conoce ninguna cantidad de alcohol segura en el embarazo: lo más seguro es no tomar nada, en ningún trimestre.',
      'detail' => NULL,
      'source' => 'CDC — Alcohol Use in Pregnancy',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'asado-tira' => 
    array (
      'name' => 'Asado de tira / vacío bien cocido',
      'synonyms' => 
      array (
        0 => 'asado de tira',
        1 => 'vacío',
        2 => 'matambre',
      ),
      'verdict' => 'safe',
      'reason' => 'Bien cocido, sin partes rosadas, es una buena fuente de hierro y proteína para el embarazo.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'atun-enlatado' => 
    array (
      'name' => 'Atún enlatado',
      'synonyms' => 
      array (
        0 => 'atún en lata',
        1 => 'atún al natural',
      ),
      'verdict' => 'precaucion',
      'reason' => 'El atún claro enlatado tiene mercurio moderado: limitalo a 2-3 latas por semana y evitá el atún blanco (albacora) más seguido.',
      'detail' => NULL,
      'source' => 'FDA/EPA — Advice about Eating Fish',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'energizante' => 
    array (
      'name' => 'Bebidas energizantes',
      'synonyms' => 
      array (
        0 => 'red bull',
        1 => 'monster',
        2 => 'speed',
      ),
      'verdict' => 'evitar',
      'reason' => 'Tienen mucha cafeína junto con otros estimulantes que no están bien estudiados en el embarazo: mejor no tomarlas.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'boldo' => 
    array (
      'name' => 'Boldo',
      'synonyms' => 
      array (
        0 => 'boldo yuyo',
      ),
      'verdict' => 'precaucion',
      'reason' => 'En infusión ocasional y suave no suele ser problema, pero evitalo en dosis altas o concentradas.',
      'detail' => NULL,
      'source' => 'MSPBS — yuyos y embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'brotes-crudos' => 
    array (
      'name' => 'Brotes crudos (alfalfa, soja)',
      'synonyms' => 
      array (
        0 => 'brotes de alfalfa',
        1 => 'brotes de soja',
        2 => 'germinados crudos',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Los brotes crudos pueden tener bacterias metidas adentro que no se van solo lavando: si podés, cocinalos antes de comerlos.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'cafe' => 
    array (
      'name' => 'Café',
      'synonyms' => 
      array (
        0 => 'café con leche',
        1 => 'café instantáneo',
        2 => 'expreso',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Una taza al día suele entrar dentro del límite seguro, pero varias tazas ya se pasan del máximo recomendado de cafeína.',
      'detail' => 'Sumá el café al resto de tu cafeína del día (tereré, mate, cocido, gaseosa cola) para no superar los 200 mg diarios.',
      'source' => 'ACOG — cafeína en el embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'carne-asada' => 
    array (
      'name' => 'Carne asada bien cocida',
      'synonyms' => 
      array (
        0 => 'asado',
        1 => 'churrasco bien hecho',
        2 => 'carne a la parrilla',
      ),
      'verdict' => 'safe',
      'reason' => 'Bien cocida, sin partes rosadas ni jugo con sangre, es una buena fuente de hierro y proteína.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'carne-jugosa' => 
    array (
      'name' => 'Carne jugosa o poco cocida (a punto, jugosa por dentro)',
      'synonyms' => 
      array (
        0 => 'carne rosada',
        1 => 'medio crudo',
        2 => 'vuelta y vuelta',
      ),
      'verdict' => 'evitar',
      'reason' => 'Si queda rosada o con jugo con sangre puede tener toxoplasma u otras bacterias: pedila siempre bien cocida en el embarazo.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'cerdo-cocido' => 
    array (
      'name' => 'Cerdo bien cocido',
      'synonyms' => 
      array (
        0 => 'asado de cerdo',
        1 => 'pechito de cerdo',
      ),
      'verdict' => 'safe',
      'reason' => 'Bien cocido por dentro, sin partes rosadas, es seguro para comer.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'cerdo-crudo' => 
    array (
      'name' => 'Cerdo poco cocido',
      'synonyms' => 
      array (
        0 => 'cerdo jugoso',
        1 => 'cerdo rosado',
      ),
      'verdict' => 'evitar',
      'reason' => 'El cerdo mal cocido puede transmitir triquinosis: pedilo o cocinalo siempre bien hecho.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'cerveza-sin-alcohol' => 
    array (
      'name' => 'Cerveza sin alcohol',
      'synonyms' => 
      array (
        0 => 'cerveza 0.0',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Suele tener un resto mínimo de alcohol (hasta 0.5%): revisá siempre la etiqueta y, si preferís no arriesgar nada, elegí otra bebida.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'chipa' => 
    array (
      'name' => 'Chipa',
      'synonyms' => 
      array (
        0 => 'chipa horneada',
        1 => 'chipa so\'o',
      ),
      'verdict' => 'safe',
      'reason' => 'Hecha con almidón, queso y huevo bien horneados, es una comida tradicional segura para comer.',
      'detail' => NULL,
      'source' => 'MSPBS — guía de alimentación en el embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'chorizo-parrillero' => 
    array (
      'name' => 'Chorizo y morcilla a la parrilla',
      'synonyms' => 
      array (
        0 => 'chorizo',
        1 => 'morcilla',
        2 => 'embutido a la parrilla',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Asegurate de que estén bien cocidos por dentro (sin partes crudas ni rosadas) antes de comerlos.',
      'detail' => 'Son ricos en grasa y sodio: además de la cocción, no conviene abusar de la cantidad.',
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'cocido' => 
    array (
      'name' => 'Cocido (mate cocido)',
      'synonyms' => 
      array (
        0 => 'mate cocido con leche',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Tiene menos cafeína que el tereré o el mate cebado, pero igual suma: no lo tomes como si no contara para tu límite diario.',
      'detail' => NULL,
      'source' => 'OMS — recomendaciones de cafeína en el embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'buffet-rotiseria' => 
    array (
      'name' => 'Comida de buffet o rotisería servida hace rato',
      'synonyms' => 
      array (
        0 => 'buffet frío',
        1 => 'comida de rotisería del mediodía a la noche',
      ),
      'verdict' => 'precaucion',
      'reason' => 'La comida que quedó mucho tiempo sin estar bien caliente o bien fría tiene más riesgo de intoxicación: preferí comida recién hecha o bien recalentada.',
      'detail' => NULL,
      'source' => 'MSPBS — higiene alimentaria',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'frito-callejero' => 
    array (
      'name' => 'Comida frita de kiosco o puesto callejero',
      'synonyms' => 
      array (
        0 => 'pastelitos fritos de la calle',
        1 => 'empanadas fritas de puesto',
      ),
      'verdict' => 'precaucion',
      'reason' => 'La higiene y el aceite reutilizado varían mucho de un puesto a otro: preferí lugares de confianza y comida bien caliente y recién hecha.',
      'detail' => NULL,
      'source' => 'MSPBS — higiene alimentaria',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'edulcorantes' => 
    array (
      'name' => 'Edulcorantes artificiales (stevia, sucralosa, aspartamo)',
      'synonyms' => 
      array (
        0 => 'stevia',
        1 => 'sucralosa',
        2 => 'aspartamo',
        3 => 'edulcorante de mesa',
      ),
      'verdict' => 'safe',
      'reason' => 'Con moderación y dentro de las cantidades habituales de uso diario, se consideran seguros en el embarazo.',
      'detail' => NULL,
      'source' => 'FDA — food additives in pregnancy',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'ensalada-afuera' => 
    array (
      'name' => 'Ensaladas crudas fuera de casa (de origen dudoso)',
      'synonyms' => 
      array (
        0 => 'ensalada de buffet',
        1 => 'ensalada de un puesto callejero',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Si no sabés cómo lavaron las verduras, hay algo más de riesgo de toxoplasmosis o bacterias: preferí lugares de confianza o pedí que estén bien lavadas.',
      'detail' => NULL,
      'source' => 'MSPBS — prevención de toxoplasmosis',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'fiambres' => 
    array (
      'name' => 'Fiambres y embutidos fríos (jamón, salame, mortadela)',
      'synonyms' => 
      array (
        0 => 'jamón crudo',
        1 => 'salame',
        2 => 'mortadela',
        3 => 'queso de chancho',
        4 => 'jamón cocido en fetas',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Pueden tener listeria: si los vas a comer, calentalos hasta que humeen (por ejemplo en un sandwich caliente) en vez de comerlos fríos directo del paquete.',
      'detail' => 'El riesgo es mayor en fiambres artesanales guardados sin buena cadena de frío que en un paquete comercial recién abierto.',
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'frutas-lavadas' => 
    array (
      'name' => 'Frutas bien lavadas en general',
      'synonyms' => 
      array (
        0 => 'manzana',
        1 => 'banana',
        2 => 'guayaba',
        3 => 'mango',
      ),
      'verdict' => 'safe',
      'reason' => 'Lavadas bajo el chorro de agua antes de comer, son una parte importante y segura de tu alimentación diaria.',
      'detail' => NULL,
      'source' => 'Mayo Clinic — Pregnancy nutrition',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'gaseosa-cola' => 
    array (
      'name' => 'Gaseosas con cafeína (cola)',
      'synonyms' => 
      array (
        0 => 'coca cola',
        1 => 'pepsi',
        2 => 'gaseosa cola',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Aportan cafeína y bastante azúcar: una de vez en cuando está bien, pero no las tomes todos los días sumadas a tereré, mate y café.',
      'detail' => NULL,
      'source' => 'ACOG — cafeína en el embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'huevo-cocido' => 
    array (
      'name' => 'Huevo bien cocido',
      'synonyms' => 
      array (
        0 => 'huevo duro',
        1 => 'huevo frito bien hecho',
        2 => 'revuelto',
      ),
      'verdict' => 'safe',
      'reason' => 'Cociná la clara y la yema hasta que estén firmes; así evitás el riesgo de salmonela.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'huevo-crudo' => 
    array (
      'name' => 'Huevo crudo o poco cocido (mayonesa casera, masa cruda)',
      'synonyms' => 
      array (
        0 => 'mayonesa casera',
        1 => 'huevo a la copa muy líquido',
        2 => 'masa de torta cruda',
      ),
      'verdict' => 'precaucion',
      'reason' => 'El huevo crudo o muy líquido puede tener salmonela: usá mayonesa comercial pasteurizada en vez de casera y evitá probar masa cruda.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'higado' => 
    array (
      'name' => 'Hígado (vacuno o de pollo)',
      'synonyms' => 
      array (
        0 => 'hígado a la plancha',
        1 => 'higadito',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Tiene mucha vitamina A: comelo de vez en cuando, no como plato de todas las semanas.',
      'detail' => 'Un exceso de vitamina A (retinol) de origen animal se asocia a riesgos para el desarrollo del bebé.',
      'source' => 'NHS — vitamin A in pregnancy',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'jugo-callejero' => 
    array (
      'name' => 'Jugo de fruta exprimido en la calle',
      'synonyms' => 
      array (
        0 => 'jugo de naranja del puesto',
        1 => 'licuado callejero',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Fijate que la fruta y el hielo (si lleva) se vean limpios y que el vendedor tenga buena higiene; ante la duda, preferí prepararlo vos.',
      'detail' => NULL,
      'source' => 'MSPBS — higiene alimentaria',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'jugo-natural' => 
    array (
      'name' => 'Jugos de fruta naturales (hechos en casa)',
      'synonyms' => 
      array (
        0 => 'jugo de naranja',
        1 => 'jugo de mburukuja',
      ),
      'verdict' => 'safe',
      'reason' => 'Son una buena forma de hidratarte y sumar vitaminas; preferí exprimirlos vos con fruta lavada.',
      'detail' => NULL,
      'source' => 'Mayo Clinic — Pregnancy nutrition',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'leche-cruda' => 
    array (
      'name' => 'Leche cruda (sin pasteurizar)',
      'synonyms' => 
      array (
        0 => 'leche de tambo sin hervir',
      ),
      'verdict' => 'evitar',
      'reason' => 'Puede tener bacterias como listeria o salmonela; si es la única que conseguís, hervila antes de tomarla.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'leche-pasteurizada' => 
    array (
      'name' => 'Leche pasteurizada',
      'synonyms' => 
      array (
        0 => 'leche entera',
        1 => 'leche descremada',
      ),
      'verdict' => 'safe',
      'reason' => 'Es una buena fuente de calcio; elegí siempre la que diga "pasteurizada" en el envase.',
      'detail' => NULL,
      'source' => 'Mayo Clinic — Pregnancy nutrition',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'locro' => 
    array (
      'name' => 'Locro',
      'synonyms' => 
      array (
        0 => 'locro de maíz',
      ),
      'verdict' => 'safe',
      'reason' => 'Es una comida casera segura; asegurate de que la carne que lleve esté bien cocida.',
      'detail' => NULL,
      'source' => 'MSPBS — guía de alimentación en el embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'mandioca-cocida' => 
    array (
      'name' => 'Mandioca bien cocida',
      'synonyms' => 
      array (
        0 => 'mandioca hervida',
        1 => 'mandi\'o',
      ),
      'verdict' => 'safe',
      'reason' => 'Bien hervida, es un alimento tradicional y seguro, buena fuente de energía.',
      'detail' => NULL,
      'source' => 'MSPBS — guía de alimentación en el embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'mandioca-cruda' => 
    array (
      'name' => 'Mandioca cruda o mal cocida',
      'synonyms' => 
      array (
        0 => 'mandioca a medio cocinar',
      ),
      'verdict' => 'evitar',
      'reason' => 'Cruda o mal cocida puede tener compuestos tóxicos: comela siempre bien hervida, nunca cruda.',
      'detail' => NULL,
      'source' => 'OMS — cassava/mandioca, cianógenos',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'mariscos-cocidos' => 
    array (
      'name' => 'Mariscos bien cocidos',
      'synonyms' => 
      array (
        0 => 'camarones cocidos',
        1 => 'langostinos',
        2 => 'mejillones cocidos',
      ),
      'verdict' => 'safe',
      'reason' => 'Bien cocidos, son una fuente segura de proteína y hierro.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'mariscos-crudos' => 
    array (
      'name' => 'Mariscos u ostras crudas',
      'synonyms' => 
      array (
        0 => 'ostras crudas',
        1 => 'ceviche con pescado crudo',
        2 => 'camarón crudo',
      ),
      'verdict' => 'evitar',
      'reason' => 'Crudos tienen más riesgo de bacterias y virus: en el embarazo conviene comerlos siempre bien cocidos.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'mate' => 
    array (
      'name' => 'Mate (caliente)',
      'synonyms' => 
      array (
        0 => 'mate cebado',
        1 => 'mate amargo',
        2 => 'mate dulce',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Igual que el tereré, el mate tiene cafeína: tomalo con moderación y contalo dentro de tu límite diario de cafeína.',
      'detail' => 'Evitá compartir la bombilla si alguien del grupo está resfriado o con anginas.',
      'source' => 'OMS — recomendaciones de cafeína en el embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'miel' => 
    array (
      'name' => 'Miel',
      'synonyms' => 
      array (
        0 => 'miel de abeja',
      ),
      'verdict' => 'safe',
      'reason' => 'Para la embarazada, la miel es segura; el riesgo de botulismo por miel es solo para bebés menores de un año, no para adultos.',
      'detail' => NULL,
      'source' => 'Mayo Clinic — Pregnancy nutrition',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'paico' => 
    array (
      'name' => 'Paico',
      'synonyms' => 
      array (
        0 => 'paico yuyo',
      ),
      'verdict' => 'evitar',
      'reason' => 'Se usa tradicionalmente como vermífugo fuerte y estimulante uterino: mejor no tomarlo en el embarazo.',
      'detail' => NULL,
      'source' => 'MSPBS — yuyos y embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'papaya-madura' => 
    array (
      'name' => 'Papaya / mamón maduro',
      'synonyms' => 
      array (
        0 => 'mamón maduro',
        1 => 'papaya madura',
      ),
      'verdict' => 'safe',
      'reason' => 'Bien madura, la papaya es una fruta segura y una buena fuente de fibra y vitaminas.',
      'detail' => NULL,
      'source' => 'Mayo Clinic — Pregnancy nutrition',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'papaya-verde' => 
    array (
      'name' => 'Papaya verde (no madura)',
      'synonyms' => 
      array (
        0 => 'mamón verde',
        1 => 'papaya inmadura',
      ),
      'verdict' => 'evitar',
      'reason' => 'La papaya verde tiene un látex que puede estimular el útero: comé solo la fruta bien madura.',
      'detail' => NULL,
      'source' => 'NHS — foods to avoid in pregnancy',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'pate-higado' => 
    array (
      'name' => 'Paté de hígado refrigerado',
      'synonyms' => 
      array (
        0 => 'paté untable',
        1 => 'paté de campaña',
      ),
      'verdict' => 'evitar',
      'reason' => 'Suma dos riesgos: exceso de vitamina A y más chance de listeria que un paté enlatado estable; mejor evitalo en el embarazo.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'pescado-mar-bajo-mercurio' => 
    array (
      'name' => 'Pescado de mar bajo en mercurio (merluza, corvina)',
      'synonyms' => 
      array (
        0 => 'merluza',
        1 => 'corvina',
        2 => 'abadejo',
      ),
      'verdict' => 'safe',
      'reason' => 'Son pescados de bajo mercurio: podés comerlos con tranquilidad como parte de una alimentación variada.',
      'detail' => NULL,
      'source' => 'FDA/EPA — Advice about Eating Fish',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'pescado-rio' => 
    array (
      'name' => 'Pescado de río (dorado, surubí, pacú)',
      'synonyms' => 
      array (
        0 => 'dorado',
        1 => 'surubí',
        2 => 'pacú',
        3 => 'pescado del Paraná',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Comé pescado de río 1 o 2 veces por semana, no todos los días: los peces más grandes acumulan más mercurio.',
      'detail' => 'Preferí ejemplares más chicos y variá con otros tipos de pescado y carne durante la semana.',
      'source' => 'FDA/EPA — Advice about Eating Fish',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'pescado-alto-mercurio' => 
    array (
      'name' => 'Pez espada, tiburón y atún ojo grande',
      'synonyms' => 
      array (
        0 => 'pez espada',
        1 => 'tiburón',
        2 => 'atún ojo grande',
        3 => 'atún rojo',
      ),
      'verdict' => 'evitar',
      'reason' => 'Son de los pescados con más mercurio: no se recomiendan durante el embarazo.',
      'detail' => NULL,
      'source' => 'FDA/EPA — Advice about Eating Fish',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'picante' => 
    array (
      'name' => 'Picante / ají',
      'synonyms' => 
      array (
        0 => 'comida picante',
        1 => 'ají picante',
        2 => 'salsa picante',
      ),
      'verdict' => 'safe',
      'reason' => 'El picante no le hace daño al bebé; si te da acidez o agruras, comé porciones más chicas.',
      'detail' => NULL,
      'source' => 'Mayo Clinic — Pregnancy nutrition',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'pina' => 
    array (
      'name' => 'Piña / ananá',
      'synonyms' => 
      array (
        0 => 'ananá',
      ),
      'verdict' => 'safe',
      'reason' => 'A pesar del mito, la piña en cantidades normales de comida no provoca parto ni aborto: podés comerla tranquila.',
      'detail' => NULL,
      'source' => 'NHS — foods to avoid in pregnancy',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'poleo' => 
    array (
      'name' => 'Poleo',
      'synonyms' => 
      array (
        0 => 'poleo yuyo',
      ),
      'verdict' => 'evitar',
      'reason' => 'Es un yuyo con uso tradicional abortivo: no se recomienda en ninguna cantidad durante el embarazo.',
      'detail' => NULL,
      'source' => 'MSPBS — yuyos y embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'pollo-cocido' => 
    array (
      'name' => 'Pollo bien cocido',
      'synonyms' => 
      array (
        0 => 'pollo al horno',
        1 => 'milanesa de pollo bien hecha',
      ),
      'verdict' => 'safe',
      'reason' => 'Cocido por completo (sin partes rosadas cerca del hueso), es una opción segura y liviana de proteína.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'pollo-crudo' => 
    array (
      'name' => 'Pollo crudo o poco cocido',
      'synonyms' => 
      array (
        0 => 'pollo rosado por dentro',
      ),
      'verdict' => 'evitar',
      'reason' => 'El pollo mal cocido puede tener salmonela o campylobacter: cocinalo siempre bien, sin partes rosadas.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'queso-paraguay-industrial' => 
    array (
      'name' => 'Queso Paraguay industrial (pasteurizado)',
      'synonyms' => 
      array (
        0 => 'queso Paraguay de marca',
      ),
      'verdict' => 'safe',
      'reason' => 'Hecho con leche pasteurizada, es una opción segura y parte habitual de la mesa paraguaya.',
      'detail' => NULL,
      'source' => 'MSPBS — listeriosis y embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'quesos-blandos' => 
    array (
      'name' => 'Quesos blandos con corteza (brie, camembert, azul)',
      'synonyms' => 
      array (
        0 => 'queso brie',
        1 => 'queso camembert',
        2 => 'queso azul',
        3 => 'roquefort',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Los que no son pasteurizados tienen más riesgo de listeria: si no podés confirmar que son pasteurizados, mejor no los comas crudos.',
      'detail' => 'Si están cocinados dentro de una comida caliente (bien cocidos, humeando), el riesgo baja bastante.',
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'queso-paraguay-artesanal' => 
    array (
      'name' => 'Quesú Paraguay artesanal',
      'synonyms' => 
      array (
        0 => 'queso Paraguay casero',
        1 => 'queso de campo',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Si no sabés si está hecho con leche pasteurizada, evitalo o cociná bien cualquier comida que lo lleve; el riesgo es una bacteria (listeria) que en el embarazo puede ser grave.',
      'detail' => 'Preguntá siempre si es de leche pasteurizada. El queso Paraguay industrial de marca sí suele estar pasteurizado.',
      'source' => 'MSPBS — listeriosis y embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'ruda' => 
    array (
      'name' => 'Ruda',
      'synonyms' => 
      array (
        0 => 'ruda macho',
      ),
      'verdict' => 'evitar',
      'reason' => 'Se usa tradicionalmente para "bajar" el embarazo: puede estimular el útero, así que no la tomes de ninguna forma.',
      'detail' => NULL,
      'source' => 'MSPBS — yuyos y embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'sopa-paraguaya' => 
    array (
      'name' => 'Sopa paraguaya',
      'synonyms' => 
      array (
        0 => 'sopa so\'o',
      ),
      'verdict' => 'safe',
      'reason' => 'Bien horneada, es una comida tradicional segura; tené en cuenta que es bastante calórica si comés porciones grandes seguido.',
      'detail' => NULL,
      'source' => 'MSPBS — guía de alimentación en el embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'sushi-crudo' => 
    array (
      'name' => 'Sushi con pescado crudo',
      'synonyms' => 
      array (
        0 => 'sashimi',
        1 => 'nigiri de salmón crudo',
      ),
      'verdict' => 'evitar',
      'reason' => 'El pescado crudo puede tener parásitos o bacterias: en el embarazo es más seguro dejarlo para después.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'sushi-cocido' => 
    array (
      'name' => 'Sushi vegetariano o con pescado bien cocido',
      'synonyms' => 
      array (
        0 => 'roll california con kanikama',
        1 => 'roll vegetariano',
        2 => 'roll tempura',
      ),
      'verdict' => 'safe',
      'reason' => 'Los rolls con ingredientes cocidos (kanikama, tempura, vegetales) o vegetarianos son una alternativa segura si tenés ganas de sushi.',
      'detail' => NULL,
      'source' => 'FDA — Food Safety for Moms-to-Be',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'terere' => 
    array (
      'name' => 'Tereré',
      'synonyms' => 
      array (
        0 => 'tereré con hierbas',
        1 => 'tereré con yuyos',
      ),
      'verdict' => 'precaucion',
      'reason' => 'Podés seguir tomando tereré: la yerba mate tiene cafeína, así que conviene no pasarte de 1-2 termos al día y sumarla al total de cafeína del día.',
      'detail' => 'El límite recomendado en el embarazo es de unos 200 mg de cafeína por día entre tereré, mate, cocido, café y gaseosas cola. Si le agregás yuyos, fijate también la ficha de cada yuyo: algunos no se recomiendan en el embarazo.',
      'source' => 'OMS — recomendaciones de cafeína en el embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'verduras-hoja' => 
    array (
      'name' => 'Verduras de hoja bien lavadas',
      'synonyms' => 
      array (
        0 => 'lechuga',
        1 => 'espinaca',
        2 => 'acelga',
        3 => 'rúcula',
      ),
      'verdict' => 'safe',
      'reason' => 'Lavadas bien bajo el chorro de agua, son una buena fuente de hierro y ácido fólico.',
      'detail' => NULL,
      'source' => 'Mayo Clinic — Pregnancy nutrition',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'yogur' => 
    array (
      'name' => 'Yogur',
      'synonyms' => 
      array (
        0 => 'yogur bebible',
        1 => 'yogur natural',
      ),
      'verdict' => 'safe',
      'reason' => 'Hecho con leche pasteurizada, es una opción segura y buena fuente de calcio.',
      'detail' => NULL,
      'source' => 'Mayo Clinic — Pregnancy nutrition',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'yuyos-abortivos-tradicionales' => 
    array (
      'name' => 'Yuyos "para bajar" o de uso abortivo tradicional (en general)',
      'synonyms' => 
      array (
        0 => 'yuyo para bajar',
        1 => 'remedio casero para bajar',
      ),
      'verdict' => 'evitar',
      'reason' => 'Cualquier yuyo que conozcas por su uso tradicional para "bajar" o cortar un embarazo puede ser peligroso: no lo tomes, y si ya lo tomaste contactá a tu médico/a, hospital o sanatorio.',
      'detail' => NULL,
      'source' => 'MSPBS — yuyos y embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
    'yuyos-comunes' => 
    array (
      'name' => 'Yuyos comunes del tereré (menta, cedrón, burrito)',
      'synonyms' => 
      array (
        0 => 'menta',
        1 => 'cedrón',
        2 => 'burrito',
        3 => 'yerbabuena',
      ),
      'verdict' => 'precaucion',
      'reason' => 'En las cantidades normales de un tereré no suelen dar problema, pero evitá tomarlos como infusión concentrada o "remedio" en dosis altas.',
      'detail' => NULL,
      'source' => 'MSPBS — yuyos y embarazo',
      'reviewedBy' => NULL,
      'published' => false,
      'page' => false,
    ),
  ),
);
