<?php
/**
 * GENERATED by tools/import-names.php from the app's lib/seed/names.json. Do not edit by hand:
 * fix the text in the app seed and re-run the import.
 * updated: import date; originSlugs/genderSlugs: code => URL segment; names: [{name,origin,gender,meaning}]
 * sorted A-Z; genderPages: [[origin, gender]] with their own page (>= 15 names).
 */
declare(strict_types=1);

return array (
  'updated' => '2026-09-27',
  'originSlugs' => 
  array (
    'guarani' => 'guaranies',
    'espanol' => 'espanoles',
    'biblico' => 'biblicos',
  ),
  'genderSlugs' => 
  array (
    'f' => 'nena',
    'm' => 'varon',
    'u' => 'para-cualquiera',
  ),
  'names' => 
  array (
    0 => 
    array (
      'name' => 'Alma',
      'origin' => 'espanol',
      'gender' => 'f',
      'meaning' => 'Alma, espíritu',
    ),
    1 => 
    array (
      'name' => 'Amambay',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'Helecho; también un departamento del país',
    ),
    2 => 
    array (
      'name' => 'Ana',
      'origin' => 'biblico',
      'gender' => 'f',
      'meaning' => 'Llena de gracia',
    ),
    3 => 
    array (
      'name' => 'Ara',
      'origin' => 'guarani',
      'gender' => 'u',
      'meaning' => 'El cielo y el tiempo, a la vez',
    ),
    4 => 
    array (
      'name' => 'Arami',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'Un pedacito de cielo',
    ),
    5 => 
    array (
      'name' => 'Aramí',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'Cielito',
    ),
    6 => 
    array (
      'name' => 'Benjamín',
      'origin' => 'espanol',
      'gender' => 'm',
      'meaning' => 'Hijo de la mano derecha',
    ),
    7 => 
    array (
      'name' => 'Bruno',
      'origin' => 'espanol',
      'gender' => 'm',
      'meaning' => 'De piel morena',
    ),
    8 => 
    array (
      'name' => 'Camila',
      'origin' => 'espanol',
      'gender' => 'f',
      'meaning' => 'La que está delante de Dios',
    ),
    9 => 
    array (
      'name' => 'Daniel',
      'origin' => 'biblico',
      'gender' => 'm',
      'meaning' => 'Dios es mi juez',
    ),
    10 => 
    array (
      'name' => 'David',
      'origin' => 'biblico',
      'gender' => 'm',
      'meaning' => 'Amado, el querido',
    ),
    11 => 
    array (
      'name' => 'Elías',
      'origin' => 'biblico',
      'gender' => 'm',
      'meaning' => 'El Señor es mi Dios',
    ),
    12 => 
    array (
      'name' => 'Emanuel',
      'origin' => 'biblico',
      'gender' => 'm',
      'meaning' => 'Dios con nosotros',
    ),
    13 => 
    array (
      'name' => 'Emilia',
      'origin' => 'espanol',
      'gender' => 'f',
      'meaning' => 'Esforzada, trabajadora',
    ),
    14 => 
    array (
      'name' => 'Facundo',
      'origin' => 'espanol',
      'gender' => 'm',
      'meaning' => 'Elocuente, el que habla bien',
    ),
    15 => 
    array (
      'name' => 'Gabriel',
      'origin' => 'biblico',
      'gender' => 'm',
      'meaning' => 'Fuerza de Dios',
    ),
    16 => 
    array (
      'name' => 'Gael',
      'origin' => 'espanol',
      'gender' => 'm',
      'meaning' => 'Generoso',
    ),
    17 => 
    array (
      'name' => 'Guyra',
      'origin' => 'guarani',
      'gender' => 'u',
      'meaning' => 'Pájaro, ave',
    ),
    18 => 
    array (
      'name' => 'Ignacio',
      'origin' => 'espanol',
      'gender' => 'm',
      'meaning' => 'Fuego, el que enciende',
    ),
    19 => 
    array (
      'name' => 'Isabella',
      'origin' => 'espanol',
      'gender' => 'f',
      'meaning' => 'Promesa de Dios',
    ),
    20 => 
    array (
      'name' => 'Jasy Rendy',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'Resplandor de la luna',
    ),
    21 => 
    array (
      'name' => 'Joaquín',
      'origin' => 'espanol',
      'gender' => 'm',
      'meaning' => 'Dios establecerá',
    ),
    22 => 
    array (
      'name' => 'Julieta',
      'origin' => 'espanol',
      'gender' => 'f',
      'meaning' => 'De raíz joven',
    ),
    23 => 
    array (
      'name' => 'Ka\'aguy',
      'origin' => 'guarani',
      'gender' => 'u',
      'meaning' => 'Monte, bosque',
    ),
    24 => 
    array (
      'name' => 'Kuarahy',
      'origin' => 'guarani',
      'gender' => 'm',
      'meaning' => 'El sol, que en guaraní también nombra al día',
    ),
    25 => 
    array (
      'name' => 'Kuñataĩ',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'Muchacha joven',
    ),
    26 => 
    array (
      'name' => 'Lautaro',
      'origin' => 'espanol',
      'gender' => 'm',
      'meaning' => 'Nombre mapuche, muy usado en el Cono Sur',
    ),
    27 => 
    array (
      'name' => 'Lucía',
      'origin' => 'espanol',
      'gender' => 'f',
      'meaning' => 'Luz, la que nació con la luz del día',
    ),
    28 => 
    array (
      'name' => 'Mainumby',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'Picaflor',
    ),
    29 => 
    array (
      'name' => 'Martina',
      'origin' => 'espanol',
      'gender' => 'f',
      'meaning' => 'Dedicada a Marte',
    ),
    30 => 
    array (
      'name' => 'María',
      'origin' => 'biblico',
      'gender' => 'f',
      'meaning' => 'La elegida, la amada',
    ),
    31 => 
    array (
      'name' => 'Mateo',
      'origin' => 'espanol',
      'gender' => 'm',
      'meaning' => 'Regalo de Dios',
    ),
    32 => 
    array (
      'name' => 'Noa',
      'origin' => 'biblico',
      'gender' => 'u',
      'meaning' => 'Descanso, consuelo',
    ),
    33 => 
    array (
      'name' => 'Panambi',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'Mariposa',
    ),
    34 => 
    array (
      'name' => 'Porã',
      'origin' => 'guarani',
      'gender' => 'u',
      'meaning' => 'Bello, bueno, como debe ser',
    ),
    35 => 
    array (
      'name' => 'Pyhare',
      'origin' => 'guarani',
      'gender' => 'u',
      'meaning' => 'La noche',
    ),
    36 => 
    array (
      'name' => 'Raquel',
      'origin' => 'biblico',
      'gender' => 'f',
      'meaning' => 'Oveja, mansedumbre',
    ),
    37 => 
    array (
      'name' => 'Renata',
      'origin' => 'espanol',
      'gender' => 'f',
      'meaning' => 'Nacida de nuevo',
    ),
    38 => 
    array (
      'name' => 'Ruth',
      'origin' => 'biblico',
      'gender' => 'f',
      'meaning' => 'Compañera, amiga fiel',
    ),
    39 => 
    array (
      'name' => 'Samuel',
      'origin' => 'biblico',
      'gender' => 'm',
      'meaning' => 'Dios escuchó',
    ),
    40 => 
    array (
      'name' => 'Santiago',
      'origin' => 'espanol',
      'gender' => 'm',
      'meaning' => 'El que suplanta',
    ),
    41 => 
    array (
      'name' => 'Sara',
      'origin' => 'biblico',
      'gender' => 'f',
      'meaning' => 'Princesa',
    ),
    42 => 
    array (
      'name' => 'Sofía',
      'origin' => 'espanol',
      'gender' => 'f',
      'meaning' => 'Sabiduría',
    ),
    43 => 
    array (
      'name' => 'Takuara',
      'origin' => 'guarani',
      'gender' => 'u',
      'meaning' => 'Caña, bambú: firme y flexible',
    ),
    44 => 
    array (
      'name' => 'Thiago',
      'origin' => 'espanol',
      'gender' => 'm',
      'meaning' => 'Forma brasileña de Santiago',
    ),
    45 => 
    array (
      'name' => 'Tupã',
      'origin' => 'guarani',
      'gender' => 'm',
      'meaning' => 'Dios del trueno en la cosmovisión guaraní',
    ),
    46 => 
    array (
      'name' => 'Valentina',
      'origin' => 'espanol',
      'gender' => 'f',
      'meaning' => 'Valiente, con salud',
    ),
    47 => 
    array (
      'name' => 'Yasy',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'La luna',
    ),
    48 => 
    array (
      'name' => 'Ysapy',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'El rocío de la mañana',
    ),
    49 => 
    array (
      'name' => 'Yvoty',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'Flor: es también como se dice a alguien querido',
    ),
    50 => 
    array (
      'name' => 'Ñande',
      'origin' => 'guarani',
      'gender' => 'u',
      'meaning' => 'Nuestro, lo de todos',
    ),
    51 => 
    array (
      'name' => 'Ñasaindy',
      'origin' => 'guarani',
      'gender' => 'f',
      'meaning' => 'Luz de luna',
    ),
  ),
  'genderPages' => 
  array (
  ),
);
