<?php
/**
 * Weeks keyed 1..42. Raw text only: render with e(); no embedded HTML.
 * title:string; seoTitle:string <=60; metaDescription:string 120..155, unique.
 * size:{name:string,lengthCm:?number,weightG:?number}; milestone:string.
 * sections:{bebe:string[],vos:string[],paraguay:string[]}; control/vaccine/
 * rightsMilestone/season:?string; faq:[{q:string,a:string}]; related:string[]
 * (article slugs, including planned ones); image:?string (site-relative path).
 * reviewedBy:null|{name:string,credentials:?string,registration:?string};
 * sources:[{title:string,publisher:string,url:?string,accessed:?ISO-date}]; updated:ISO-date.
 * Derive trimester with week_trimester(n), never store it. Missing measurements = null.
 * Seed-only rows deliberately have empty sections/sources; keep noindex until authored.
 * Source for seed size/milestone: app lib/weeks.ts (read-only import).
 * Re-import preserves editorial fields, refreshes size/milestone/updated; edit here.
 */
declare(strict_types=1);

return [
    1 => [
        'title' => 'Semana 1 de embarazo',
        'seoTitle' => 'Semana 1 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 1 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'todavía no hay embrión',
            'lengthCm' => null,
            'weightG' => null,
        ],
        'milestone' => 'Tu cuerpo se prepara. Las semanas se cuentan desde tu última menstruación, así que en la semana 1 todavía no hubo concepción.',
        'updated' => '2026-09-20',
    ],
    2 => [
        'title' => 'Semana 2 de embarazo',
        'seoTitle' => 'Semana 2 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 2 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'todavía no hay embrión',
            'lengthCm' => null,
            'weightG' => null,
        ],
        'milestone' => 'Es la semana de la ovulación para muchas. El cuerpo libera un óvulo que puede ser fecundado en estos días.',
        'updated' => '2026-09-20',
    ],
    3 => [
        'title' => 'Semana 3 de embarazo',
        'seoTitle' => 'Semana 3 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 3 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una semilla de chía',
            'lengthCm' => 0.01,
            'weightG' => null,
        ],
        'milestone' => 'Si hubo fecundación, el óvulo se transforma en un grupito de células que viaja hacia el útero. Todo es microscópico todavía.',
        'updated' => '2026-09-20',
    ],
    4 => [
        'title' => 'Semana 4 de embarazo',
        'seoTitle' => 'Semana 4 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 4 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una semilla de amapola',
            'lengthCm' => 0.1,
            'weightG' => null,
        ],
        'milestone' => 'El embrión se implanta en el útero. Es cuando muchas notan el atraso y un test puede dar positivo.',
        'updated' => '2026-09-20',
    ],
    5 => [
        'title' => 'Semana 5 de embarazo',
        'seoTitle' => 'Semana 5 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 5 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un grano de sésamo',
            'lengthCm' => 0.2,
            'weightG' => 1,
        ],
        'milestone' => 'Empieza a formarse el tubo neural, que será el cerebro y la médula. El corazón ya está dando sus primeros latidos.',
        'updated' => '2026-09-20',
    ],
    6 => [
        'title' => 'Semana 6 de embarazo',
        'seoTitle' => 'Semana 6 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 6 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una lenteja',
            'lengthCm' => 0.4,
            'weightG' => 1,
        ],
        'milestone' => 'El corazón late más fuerte y se forman los brotes de los brazos y las piernas. La carita empieza a definirse.',
        'updated' => '2026-09-20',
    ],
    7 => [
        'title' => 'Semana 7 de embarazo',
        'seoTitle' => 'Semana 7 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 7 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un grano de maíz',
            'lengthCm' => 1,
            'weightG' => 1,
        ],
        'milestone' => 'El cerebro crece rápido y se forman manos y pies en pequeños brotes. El embrión se mueve, aunque todavía no lo sentís.',
        'updated' => '2026-09-20',
    ],
    8 => [
        'title' => 'Semana 8 de embarazo',
        'seoTitle' => 'Semana 8 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 8 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un poroto',
            'lengthCm' => 1.6,
            'weightG' => 1,
        ],
        'milestone' => 'Ya tiene parpados, labio superior y la punta de la nariz. Los dedos empiezan a separarse.',
        'updated' => '2026-09-20',
    ],
    9 => [
        'title' => 'Semana 9 de embarazo',
        'seoTitle' => 'Semana 9 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 9 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una aceituna',
            'lengthCm' => 2.3,
            'weightG' => 2,
        ],
        'milestone' => 'Termina la etapa de embrión: ahora se llama feto. Tiene todos los órganos principales esbozados.',
        'updated' => '2026-09-20',
    ],
    10 => [
        'title' => 'Semana 10 de embarazo',
        'seoTitle' => 'Semana 10 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 10 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una guinda',
            'lengthCm' => 3.1,
            'weightG' => 4,
        ],
        'milestone' => 'Se forman las uñas y empieza a funcionar el sistema digestivo. Los huesos comienzan a endurecerse.',
        'updated' => '2026-09-20',
    ],
    11 => [
        'title' => 'Semana 11 de embarazo',
        'seoTitle' => 'Semana 11 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 11 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una frutilla',
            'lengthCm' => 4.1,
            'weightG' => 7,
        ],
        'milestone' => 'El bebé ya abre y cierra las manitos y mueve la cabeza. La placenta crece para nutrirlo mejor.',
        'updated' => '2026-09-20',
    ],
    12 => [
        'title' => 'Semana 12 de embarazo',
        'seoTitle' => 'Semana 12 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 12 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una lima',
            'lengthCm' => 5.4,
            'weightG' => 14,
        ],
        'milestone' => 'Casi todos los órganos están formados. Los reflejos aparecen y el bebé puede mover los dedos.',
        'updated' => '2026-09-20',
    ],
    13 => [
        'title' => 'Semana 13 de embarazo',
        'seoTitle' => 'Semana 13 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 13 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un durazno',
            'lengthCm' => 7.4,
            'weightG' => 23,
        ],
        'milestone' => 'Última semana del primer trimestre. Ya tiene huellas digitales y las cuerdas vocales se están formando.',
        'updated' => '2026-09-20',
    ],
    14 => [
        'title' => 'Semana 14 de embarazo',
        'seoTitle' => 'Semana 14 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 14 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un limón',
            'lengthCm' => 8.7,
            'weightG' => 43,
        ],
        'milestone' => 'Arranca el segundo trimestre, el más llevadero para muchas. El bebé hace muecas y puede chuparse el dedo.',
        'updated' => '2026-09-20',
    ],
    15 => [
        'title' => 'Semana 15 de embarazo',
        'seoTitle' => 'Semana 15 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 15 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una mandarina',
            'lengthCm' => 10.1,
            'weightG' => 70,
        ],
        'milestone' => 'El bebé percibe la luz aunque tenga los ojos cerrados y empieza a oír sonidos de tu cuerpo.',
        'updated' => '2026-09-20',
    ],
    16 => [
        'title' => 'Semana 16 de embarazo',
        'seoTitle' => 'Semana 16 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 16 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una palta pequeña',
            'lengthCm' => 11.6,
            'weightG' => 100,
        ],
        'milestone' => 'Los músculos de la cara ya funcionan y el cuello se sostiene mejor. Algunas mamás empiezan a intuir movimientos.',
        'updated' => '2026-09-20',
    ],
    17 => [
        'title' => 'Semana 17 de embarazo',
        'seoTitle' => 'Semana 17 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 17 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una granada',
            'lengthCm' => 13,
            'weightG' => 140,
        ],
        'milestone' => 'Se forma la grasa que le dará calor al nacer. El esqueleto, antes blando, se va volviendo hueso.',
        'updated' => '2026-09-20',
    ],
    18 => [
        'title' => 'Semana 18 de embarazo',
        'seoTitle' => 'Semana 18 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 18 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un mamón pequeño',
            'lengthCm' => 14.2,
            'weightG' => 190,
        ],
        'milestone' => 'El bebé se mueve bastante: estira, patea y se da vuelta. Sus oídos ya están en su lugar y oye mejor.',
        'updated' => '2026-09-20',
    ],
    19 => [
        'title' => 'Semana 19 de embarazo',
        'seoTitle' => 'Semana 19 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 19 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un mango',
            'lengthCm' => 15.3,
            'weightG' => 240,
        ],
        'milestone' => 'Una capa protectora cubre su piel. Si es nena, ya tiene formados sus óvulos; si es varón, sus genitales se definen.',
        'updated' => '2026-09-20',
    ],
    20 => [
        'title' => 'Semana 20 de embarazo',
        'seoTitle' => 'Semana 20 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 20 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [
                'En la semana 20 de embarazo, tu bebé tiene aproximadamente el tamaño de una banana: unos 25,6 cm y 300 g como referencia. Traga líquido amniótico y sus riñones ya producen pis. Se mueve, estira los brazos y las piernas, y quizá empieces a reconocer esas primeras pataditas. Estás en el segundo trimestre, cerca de la mitad del embarazo, y es una etapa habitual para la ecografía que revisa su anatomía.',
                'Su piel todavía es fina y va quedando protegida por una sustancia blanquecina y grasosa llamada vérnix. También tiene un vello suave, el lanugo, que forma parte de esta etapa del desarrollo. Los órganos siguen madurando y el bebé alterna momentos de actividad y descanso. Los movimientos que se ven en una ecografía pueden ser más amplios que los que vos alcanzás a sentir.',
                'Los 25,6 cm representan una longitud aproximada de cabeza a pies; el peso también es orientativo. En la ecografía se toman distintas medidas, como las de la cabeza, el abdomen y el fémur, para valorar el crecimiento. Una diferencia con el tamaño de la fruta no significa por sí sola un problema: importa cómo interpreta el equipo el conjunto de las medidas.',
                'La ecografía morfológica suele realizarse alrededor de las semanas 18 a 24, según la indicación y el servicio. Revisa estructuras como el cerebro, la columna, el corazón, los riñones y las extremidades, además de la placenta y el líquido amniótico. A veces hace falta otra visita para completar imágenes por la posición del bebé. Un resultado tranquilizador es valioso, aunque ningún estudio detecta todas las alteraciones.',
                'Mi Bebé muestra la semana que está transcurriendo. Por eso, semana 20 equivale a 19 semanas completas más los días: de 19+0 a 19+6. Si en tu carné figura 19 y en la app 20, puede ser simplemente esa diferencia de presentación. Para coordinar estudios, usá la edad gestacional y la fecha probable de parto que dejó registradas tu equipo.',
            ],
            'vos' => [
                'Muchas mujeres sienten menos náuseas y algo más de energía que al comienzo, aunque el cansancio puede seguir. La panza suele hacerse más visible y pueden aparecer tirones breves a los costados al levantarte o cambiar de posición. También son frecuentes la acidez, el estreñimiento y las molestias leves de espalda. La forma y el tamaño de la panza varían entre personas y entre embarazos.',
                'También podés notar una línea más oscura en el abdomen o cambios de color alrededor de los pezones. Es común tener más flujo vaginal claro o blanquecino, sin olor fuerte ni picazón. Si aparece mal olor, picazón o ardor al orinar, consultá para que te evalúen. Una salida de líquido acuoso que moja la ropa requiere atención pronta, aunque no duela. Contar cómo empezó y qué notaste ayuda al equipo a distinguir lo que está pasando.',
                'Para estar más cómoda, probá comer porciones pequeñas y evitar acostarte justo después de comer si tenés acidez. El agua, los alimentos con fibra y el movimiento suave suelen ayudar con el estreñimiento. Cambiar de postura con calma, hacer pausas y usar una almohada de apoyo al descansar puede aliviar la espalda. Si una molestia persiste o empeora, comentala en tu atención prenatal.',
                'Los primeros movimientos suelen sentirse entre las semanas 16 y 24. En el primer embarazo puede llevar más tiempo reconocerlos: a veces parecen burbujas, un aleteo o pequeños golpecitos. La posición de la placenta también influye en cuánto percibís. Al principio pueden ser irregulares. Si a las 24 semanas todavía no sentiste movimientos, avisá a tu equipo; si notás una disminución clara respecto de lo habitual, consultá enseguida.',
                'El sangrado vaginal, la pérdida de líquido, el dolor abdominal intenso o persistente, la fiebre o un dolor de cabeza fuerte con visión borrosa necesitan atención sin esperar al próximo control. Tampoco atribuyas al embarazo una falta de aire intensa o un dolor en el pecho. Buscá atención inmediata y revisá [las señales de alarma](/salud/senales-de-alarma/), también entre las lecturas relacionadas.',
            ],
            'paraguay' => [
                'En un control de esta etapa suelen revisar cómo te sentís, tu presión arterial, el peso, el crecimiento del útero y los latidos del bebé. También repasan los análisis y los estudios pendientes. Llevá tu carné perinatal y los informes que ya tengas, para que las indicaciones queden reunidas y puedas ver qué sigue después de la consulta.',
                'Antes de salir, preguntá cuándo te corresponde la morfológica, dónde reservarla y si necesita alguna preparación. Otras preguntas útiles son qué mostraron tus análisis, qué molestias conviene vigilar y cuándo será el siguiente control. Acercá también tu registro de vacunas: el equipo puede revisar cuáles del PAI te corresponden durante el embarazo y en qué momento aplicarlas.',
                'Si trabajás, la Ley 7383/2024 contempla hasta cuatro horas remuneradas para controles prenatales; confirmá alcance y constancias con tu empleador. La Ley 5099/2013 establece la gratuidad de las prestaciones del MSPBS. Para organizar la ecografía, averiguá dónde se realiza y cómo conseguir turno; si tu atención es por IPS o en un sanatorio privado, consultá la cobertura del estudio.',
                'Con el calor de Paraguay, tené agua potable a mano, buscá sombra y hacé pausas si pasás tiempo al aire libre. El tereré puede contener cafeína y yuyos: contá también el mate, el cocido y el café cuando converses sobre tu consumo. Para reducir criaderos de mosquitos, vaciá recipientes con agua acumulada y mantené tapados los depósitos. Usá barreras como mosquiteros y ropa que cubra la piel.',
            ],
        ],
        'control' => 'La ecografía morfológica suele hacerse aproximadamente entre las semanas 18 y 24; revisa la anatomía del bebé, la placenta y el líquido amniótico. Coordiná la fecha en tu control.',
        'vaccine' => 'Llevá tu registro de vacunas al control para revisar con el equipo cuáles del PAI te corresponden y cuándo aplicarlas.',
        'rightsMilestone' => 'Ley 7383/2024: hasta cuatro horas remuneradas para controles prenatales; confirmá alcance y constancias con tu empleador.',
        'season' => 'En días de calor, tené agua potable a mano y buscá sombra. Para reducir criaderos de mosquitos, vaciá el agua acumulada y tapá los depósitos.',
        'faq' => [
            [
                'q' => '¿Cuánto mide y pesa el bebé en la semana 20?',
                'a' => 'Como referencia, mide unos 25,6 cm de cabeza a pies y pesa alrededor de 300 g, parecido a una banana. Son valores aproximados; en la ecografía se valoran varias medidas para seguir su crecimiento.',
            ],
            [
                'q' => '¿Qué síntomas son normales en la semana 20?',
                'a' => 'Son comunes la acidez, el estreñimiento, el cansancio y las molestias leves de espalda. Sangrado, pérdida de líquido, dolor fuerte o dolor de cabeza intenso con visión borrosa necesitan atención inmediata; revisá [las señales de alarma](/salud/senales-de-alarma/).',
            ],
            [
                'q' => '¿Cuándo se hace la ecografía morfológica?',
                'a' => 'Suele hacerse aproximadamente entre las semanas 18 y 24, según tu indicación y el servicio. Revisa la anatomía del bebé, su crecimiento, la placenta y el líquido amniótico; preguntá por el turno en tu control.',
            ],
            [
                'q' => '¿Cuándo se sienten los movimientos del bebé?',
                'a' => 'Suelen empezar a percibirse entre las semanas 16 y 24, a veces más tarde dentro de ese rango en el primer embarazo. Si a las 24 semanas no sentiste movimientos, avisá a tu equipo. Una disminución clara de lo habitual requiere consulta inmediata.',
            ],
            [
                'q' => '¿Por qué mi carné dice 19 semanas y la app semana 20?',
                'a' => 'La app muestra la semana que transcurre: 19 semanas completas más entre cero y seis días corresponden a la semana 20.',
            ],
        ],
        'related' => [
            'licencia-de-maternidad',
            'senales-de-alarma',
            'vacunas-en-el-embarazo',
        ],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [
            [
                'title' => 'Recomendaciones de la OMS sobre atención prenatal para una experiencia positiva del embarazo',
                'publisher' => 'Organización Mundial de la Salud (OMS)',
                'url' => null,
                'accessed' => null,
            ],
            [
                'title' => 'Orientaciones para el control prenatal',
                'publisher' => 'Ministerio de Salud Pública y Bienestar Social (MSPBS)',
                'url' => null,
                'accessed' => null,
            ],
            [
                'title' => 'Ley 7383/2024 — permisos para controles prenatales',
                'publisher' => 'Congreso de la Nación Paraguaya',
                'url' => null,
                'accessed' => null,
            ],
            [
                'title' => 'Ley 5099/2013 — gratuidad MSPBS',
                'publisher' => 'Congreso de la Nación Paraguaya',
                'url' => null,
                'accessed' => null,
            ],
        ],
        'size' => [
            'name' => 'una banana',
            'lengthCm' => 25.6,
            'weightG' => 300,
        ],
        'milestone' => 'Llegaste a la mitad del camino. El bebé traga líquido y sus riñones ya producen pis.',
        'updated' => '2026-09-20',
    ],
    21 => [
        'title' => 'Semana 21 de embarazo',
        'seoTitle' => 'Semana 21 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 21 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una mazorca de choclo',
            'lengthCm' => 26.7,
            'weightG' => 360,
        ],
        'milestone' => 'Los movimientos se vuelven más fuertes y seguidos. Tiene momentos de actividad y de descanso.',
        'updated' => '2026-09-20',
    ],
    22 => [
        'title' => 'Semana 22 de embarazo',
        'seoTitle' => 'Semana 22 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 22 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un mamón mediano',
            'lengthCm' => 27.8,
            'weightG' => 430,
        ],
        'milestone' => 'Sus rasgos ya son los que tendrá al nacer: cejas, labios y los primeros pelitos.',
        'updated' => '2026-09-20',
    ],
    23 => [
        'title' => 'Semana 23 de embarazo',
        'seoTitle' => 'Semana 23 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 23 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un pomelo',
            'lengthCm' => 28.9,
            'weightG' => 501,
        ],
        'milestone' => 'Empieza a escuchar tu voz, tu corazón y los ruidos de afuera. La audición se afina cada semana.',
        'updated' => '2026-09-20',
    ],
    24 => [
        'title' => 'Semana 24 de embarazo',
        'seoTitle' => 'Semana 24 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 24 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una mandioca',
            'lengthCm' => 30,
            'weightG' => 600,
        ],
        'milestone' => 'Los pulmones desarrollan las ramitas por donde después entrará el aire. La carita está casi completa.',
        'updated' => '2026-09-20',
    ],
    25 => [
        'title' => 'Semana 25 de embarazo',
        'seoTitle' => 'Semana 25 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 25 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un coco',
            'lengthCm' => 34.6,
            'weightG' => 660,
        ],
        'milestone' => 'Va ganando grasa y la piel se pone menos arrugada. Reacciona a tu voz con movimientos.',
        'updated' => '2026-09-20',
    ],
    26 => [
        'title' => 'Semana 26 de embarazo',
        'seoTitle' => 'Semana 26 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 26 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un repollo pequeño',
            'lengthCm' => 35.6,
            'weightG' => 760,
        ],
        'milestone' => 'Abre los ojos por primera vez y responde a la luz fuerte sobre la panza. Los pulmones siguen madurando.',
        'updated' => '2026-09-20',
    ],
    27 => [
        'title' => 'Semana 27 de embarazo',
        'seoTitle' => 'Semana 27 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 27 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una coliflor',
            'lengthCm' => 36.6,
            'weightG' => 875,
        ],
        'milestone' => 'Última semana del segundo trimestre. El bebé tiene hipo a veces; vas a sentir pequeños saltitos rítmicos.',
        'updated' => '2026-09-20',
    ],
    28 => [
        'title' => 'Semana 28 de embarazo',
        'seoTitle' => 'Semana 28 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 28 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una berenjena grande',
            'lengthCm' => 37.6,
            'weightG' => 1005,
        ],
        'milestone' => 'Arranca el tercer trimestre. El bebé sueña, parpadea y su cerebro forma surcos cada vez más complejos.',
        'updated' => '2026-09-20',
    ],
    29 => [
        'title' => 'Semana 29 de embarazo',
        'seoTitle' => 'Semana 29 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 29 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un coco grande',
            'lengthCm' => 38.6,
            'weightG' => 1153,
        ],
        'milestone' => 'Los músculos y los pulmones siguen madurando. Sus pataditas son cada vez más firmes.',
        'updated' => '2026-09-20',
    ],
    30 => [
        'title' => 'Semana 30 de embarazo',
        'seoTitle' => 'Semana 30 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 30 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un repollo',
            'lengthCm' => 39.9,
            'weightG' => 1319,
        ],
        'milestone' => 'La médula ósea ya fabrica glóbulos rojos. El bebé regula mejor su propia temperatura.',
        'updated' => '2026-09-20',
    ],
    31 => [
        'title' => 'Semana 31 de embarazo',
        'seoTitle' => 'Semana 31 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 31 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un coco con su cáscara',
            'lengthCm' => 41.1,
            'weightG' => 1502,
        ],
        'milestone' => 'Puede mover la cabeza de lado a lado y patalear con fuerza. Ocupa cada vez más espacio.',
        'updated' => '2026-09-20',
    ],
    32 => [
        'title' => 'Semana 32 de embarazo',
        'seoTitle' => 'Semana 32 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 32 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una lechuga',
            'lengthCm' => 42.4,
            'weightG' => 1702,
        ],
        'milestone' => 'Practica respirar moviendo el diafragma y ya tiene uñas en los deditos. Muchos bebés se acomodan cabeza abajo.',
        'updated' => '2026-09-20',
    ],
    33 => [
        'title' => 'Semana 33 de embarazo',
        'seoTitle' => 'Semana 33 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 33 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un ananá',
            'lengthCm' => 43.7,
            'weightG' => 1918,
        ],
        'milestone' => 'Los huesos del cráneo todavía están blandos y separados para poder pasar por el parto. El sistema inmune se fortalece.',
        'updated' => '2026-09-20',
    ],
    34 => [
        'title' => 'Semana 34 de embarazo',
        'seoTitle' => 'Semana 34 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 34 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un melón pequeño',
            'lengthCm' => 45,
            'weightG' => 2146,
        ],
        'milestone' => 'Los pulmones están casi listos. Si naciera ahora, tendría muy buenas chances con apoyo médico.',
        'updated' => '2026-09-20',
    ],
    35 => [
        'title' => 'Semana 35 de embarazo',
        'seoTitle' => 'Semana 35 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 35 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un melón',
            'lengthCm' => 46.2,
            'weightG' => 2383,
        ],
        'milestone' => 'Engorda rápido y la panza ya casi no le deja espacio para grandes giros. Sus riñones están completos.',
        'updated' => '2026-09-20',
    ],
    36 => [
        'title' => 'Semana 36 de embarazo',
        'seoTitle' => 'Semana 36 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 36 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una lechuga grande',
            'lengthCm' => 47.4,
            'weightG' => 2622,
        ],
        'milestone' => 'Se considera casi a término. La mayoría ya está cabeza abajo, lista para nacer.',
        'updated' => '2026-09-20',
    ],
    37 => [
        'title' => 'Semana 37 de embarazo',
        'seoTitle' => 'Semana 37 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 37 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una sandía pequeña',
            'lengthCm' => 48.6,
            'weightG' => 2859,
        ],
        'milestone' => 'A partir de ahora se considera a término temprano. El bebé practica respirar y agarrar con la mano.',
        'updated' => '2026-09-20',
    ],
    38 => [
        'title' => 'Semana 38 de embarazo',
        'seoTitle' => 'Semana 38 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 38 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'un zapallo pequeño',
            'lengthCm' => 49.8,
            'weightG' => 3083,
        ],
        'milestone' => 'Casi todo está listo. Sigue acumulando grasa que le dará calor y energía después de nacer.',
        'updated' => '2026-09-20',
    ],
    39 => [
        'title' => 'Semana 39 de embarazo',
        'seoTitle' => 'Semana 39 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 39 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una sandía mediana',
            'lengthCm' => 50.7,
            'weightG' => 3288,
        ],
        'milestone' => 'Bebé a término completo. Los pulmones y el cerebro siguen afinándose hasta el último día.',
        'updated' => '2026-09-20',
    ],
    40 => [
        'title' => 'Semana 40 de embarazo',
        'seoTitle' => 'Semana 40 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 40 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una sandía',
            'lengthCm' => 51.2,
            'weightG' => 3462,
        ],
        'milestone' => 'Llegó tu fecha probable de parto. Recordá que es una estimación: muchos bebés nacen unos días antes o después.',
        'updated' => '2026-09-20',
    ],
    41 => [
        'title' => 'Semana 41 de embarazo',
        'seoTitle' => 'Semana 41 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 41 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una sandía grande',
            'lengthCm' => 51.7,
            'weightG' => 3597,
        ],
        'milestone' => 'El bebé sigue creciendo un poquito. El equipo de salud vigila de cerca que todo siga bien.',
        'updated' => '2026-09-20',
    ],
    42 => [
        'title' => 'Semana 42 de embarazo',
        'seoTitle' => 'Semana 42 de embarazo: tu bebé y vos',
        'metaDescription' => 'Semana 42 de embarazo en Paraguay: conocé el desarrollo de tu bebé, prepará tus preguntas para el control y seguí esta etapa con Mi Bebé.',
        'sections' => [
            'bebe' => [],
            'vos' => [],
            'paraguay' => [],
        ],
        'control' => null,
        'vaccine' => null,
        'rightsMilestone' => null,
        'season' => null,
        'faq' => [],
        'related' => [],
        'image' => null,
        'reviewedBy' => null,
        'sources' => [],
        'size' => [
            'name' => 'una sandía grande y madura',
            'lengthCm' => 51.7,
            'weightG' => 3685,
        ],
        'milestone' => 'Pocos embarazos llegan hasta acá. El nacimiento está muy cerca y el seguimiento médico es más estricto.',
        'updated' => '2026-09-20',
    ],
];
