<?php
/**
 * Trimesters keyed 1..3: title,seoTitle,metaDescription,lead:string;
 * timeline:[{week:int,what:string}] (editorial prompts, not a clinical schedule);
 * weeks:int[] DERIVED via week_trimester(), never maintain another range table;
 * faq:[{q,a}]. Additive sources:[{title,publisher,url,accessed}], reviewedBy:null,
 * updated:ISO-date. Text is plain; escape with e(). Load after lib/bootstrap.php.
 */
declare(strict_types=1);

$_trimestres = [
1 => ['title' => 'Primer trimestre de embarazo',
'seoTitle' => 'Primer trimestre: síntomas y primeros controles',
'metaDescription' => 'Conocé qué pasa en el primer trimestre de embarazo: desarrollo inicial, náuseas, primera consulta y estudios para conversar con tu equipo en Paraguay.',
'lead' => 'En el primer trimestre se forman las estructuras principales del bebé y empieza a desarrollarse la placenta. Podés sentir náuseas, sueño y sensibilidad en los pechos, aunque tener pocos síntomas también es posible. Al comienzo, el conteo incluye días anteriores a la concepción: en las semanas 1 y 2 todavía no hay embrión. Pedí el primer control cuando sepas del embarazo para revisar antecedentes, medicamentos y estudios. Acá encontrás las semanas 1 a 13 del recorrido de Mi Bebé.',
'timeline' => [['week' => 4,
'what' => 'Primer contacto: anotá el primer día de tu última menstruación, la fecha del test y los medicamentos o suplementos que usás. Pedí atención prenatal sin esperar a que crezca la panza; llevá también tus dudas sobre ácido fólico.'],
['week' => 6,
'what' => 'Consulta inicial: el equipo revisa antecedentes, presión arterial y salud general. Los análisis de sangre y orina ayudan a conocer el grupo sanguíneo, detectar anemia y buscar infecciones que pueden necesitar tratamiento aunque no den síntomas.'],
['week' => 8,
'what' => 'Vacunas: acercá tu registro para revisar cuáles corresponden durante el embarazo y cuáles conviene dejar para después. La indicación depende de tus antecedentes y del esquema vigente del PAI; anotá la próxima fecha indicada.'],
['week' => 10,
'what' => 'Trabajo y controles: la Ley 7383/2024 contempla hasta cuatro horas remuneradas para controles prenatales; confirmá alcance y constancias con tu empleador. Podés preparar tus preguntas desde el [hub de derechos](/derechos/).'],
['week' => 12,
'what' => 'Ecografía del primer trimestre: permite valorar la edad gestacional y el número de bebés. Algunos estudios de tamizaje se ofrecen alrededor de las 11 a 14 semanas completas, según la evaluación y el servicio. Preguntá qué busca cada estudio: un resultado de tamizaje estima probabilidades, no confirma un diagnóstico. Leé más en la [semana 12](/semana/12/).'],
['week' => 13,
'what' => 'Cierre de esta etapa: repasá los resultados con tu equipo y dejá anotada la siguiente consulta. Si las náuseas dificultan comer o tomar líquidos, pedí ayuda; no tenés que soportarlas hasta el segundo trimestre.']],
'faq' => [['q' => '¿Cuándo se ve el embarazo en una ecografía?',
'a' => 'Depende de la edad gestacional real y del tipo de ecografía. Si se hace muy temprano, puede no mostrar todavía todo lo esperado. El equipo interpreta las imágenes junto con tus fechas y síntomas y te indica si hace falta repetirla.'],
['q' => '¿Es normal no tener náuseas?',
'a' => 'Sí, los síntomas varían mucho. Su presencia o ausencia no permite saber por sí sola cómo evoluciona el embarazo. Los controles aportan información que las sensaciones del cuerpo no pueden reemplazar.'],
['q' => '¿Qué puedo hacer si me cuesta comer?',
'a' => 'Probá porciones pequeñas, alimentos que toleres y sorbos frecuentes de agua. Evitá los olores que te provocan náuseas. Si vomitás todo, orinás poco o te sentís muy débil, buscá atención pronta.'],
['q' => '¿Qué molestias necesitan atención inmediata?',
'a' => 'Buscá atención inmediata ante sangrado abundante, dolor abdominal fuerte, desmayo o fiebre. Un dolor intenso de un lado, especialmente con mareo, también requiere evaluación urgente. Tené a mano las [señales de alarma](/salud/senales-de-alarma/).']],
'sources' => [['title' => 'Recomendaciones de la OMS sobre atención prenatal para una experiencia positiva del embarazo',
'publisher' => 'Organización Mundial de la Salud (OMS)',
'url' => null,
'accessed' => null],
['title' => 'Orientaciones vigentes sobre control prenatal y vacunación durante el embarazo',
'publisher' => 'Ministerio de Salud Pública y Bienestar Social (MSPBS)',
'url' => null,
'accessed' => null],
['title' => 'Ley 7383/2024 — permisos para controles prenatales (nota oficial del MTESS)', 'publisher' => 'Ministerio de Trabajo, Empleo y Seguridad Social (MTESS)', 'url' => 'https://www.mtess.gov.py/?p=30138', 'accessed' => '2026-09-20']]],
2 => ['title' => 'Segundo trimestre de embarazo',
'seoTitle' => 'Segundo trimestre: movimientos y estudios',
'metaDescription' => 'Recorré el segundo trimestre: primeras pataditas, ecografía de anatomía, controles y análisis de glucosa. Prepará tus preguntas para cada consulta.',
'lead' => 'En el segundo trimestre el bebé crece, mueve sus extremidades y sigue madurando. La panza suele hacerse más visible y podés empezar a reconocer sus movimientos. Muchas mujeres sienten menos náuseas, aunque el cansancio y la acidez pueden continuar. Los controles acompañan tu salud y el crecimiento del bebé; la ecografía de esta etapa revisa su anatomía. Este hub reúne las semanas 14 a 27 de Mi Bebé, con temas para llevar a la consulta.',
'timeline' => [['week' => 14,
'what' => 'Seguimiento: conversá sobre alimentación, actividad física y molestias que continúan. En los controles se revisan la presión arterial, el peso y los resultados pendientes; más adelante también se sigue el crecimiento del útero.'],
['week' => 16,
'what' => 'Primeras pataditas: suelen reconocerse entre las 16 y 24 semanas completas. Al principio pueden parecer burbujas y no sentirse todos los días. Si a las 24 semanas no sentiste movimientos, avisá a tu equipo. La [semana 16](/semana/16/) explica este comienzo.'],
['week' => 18,
'what' => 'Organización laboral: si necesitás tiempo para asistir a controles, prepará las fechas y preguntá qué constancia presentar. La Ley 7383/2024 prevé hasta cuatro horas remuneradas para controles prenatales; confirmá su alcance y los requisitos con tu empleador.'],
['week' => 20,
'what' => 'Ecografía morfológica: suele realizarse aproximadamente entre las 18 y 24 semanas completas. Revisa estructuras del bebé, placenta y líquido amniótico; a veces se necesitan más imágenes por su posición. Ninguna ecografía detecta todas las alteraciones. Encontrá preguntas concretas en la [semana 20](/semana/20/).'],
['week' => 24,
'what' => 'Glucosa: el estudio para detectar diabetes gestacional suele plantearse entre las 24 y 28 semanas completas, o antes si hay motivos clínicos. Puede identificar alteraciones sin síntomas. Seguí la preparación que te indique el servicio y llevá el resultado al control.'],
['week' => 26,
'what' => 'Vacunación: revisá con el equipo las dosis registradas y las pendientes para esta etapa según el PAI. Si quedó una indicación sin cumplir, comentá el motivo para reorganizarla; no deduzcas el esquema por la semana que aparece en la pantalla.'],
['week' => 27,
'what' => 'Próxima etapa: consultá por los resultados de glucosa y anemia y por el seguimiento de tu grupo sanguíneo y factor Rh. Si sos Rh negativa, el equipo evalúa los anticuerpos y la necesidad de prevención específica; esa prevención no es una vacuna.']],
'faq' => [['q' => '¿El tamaño de mi panza muestra cuánto crece el bebé?',
'a' => 'No por sí solo. Influyen tu contextura, embarazos anteriores y la posición del bebé, entre otros factores. El crecimiento se valora en los controles y con ecografía cuando corresponde, no comparando fotos de panzas.'],
['q' => '¿Por qué todavía no siento pataditas?',
'a' => 'En el primer embarazo puede llevar más tiempo reconocerlas; la posición de la placenta también influye. Si llegás a las 24 semanas completas sin percibirlas, avisá a tu equipo. Si ya las sentías y disminuyen claramente, consultá enseguida.'],
['q' => '¿La morfológica sirve solamente para saber el sexo?',
'a' => 'Su objetivo principal es revisar la anatomía y otras características del embarazo. La posición puede dificultar algunas imágenes y el equipo puede indicar completarlas otro día. Pedí que te expliquen qué se pudo evaluar y qué falta.'],
['q' => '¿Qué síntomas no debo atribuir al crecimiento de la panza?',
'a' => 'El dolor fuerte o persistente, sangrado, salida de líquido, dolor de cabeza intenso con visión borrosa o falta de aire marcada necesitan atención inmediata. Consultá las [señales de alarma](/salud/senales-de-alarma/) para reconocer otras situaciones urgentes.']],
'sources' => [['title' => 'Recomendaciones de la OMS sobre atención prenatal para una experiencia positiva del embarazo',
'publisher' => 'Organización Mundial de la Salud (OMS)',
'url' => null,
'accessed' => null],
['title' => 'Orientaciones vigentes sobre control prenatal y vacunación durante el embarazo',
'publisher' => 'Ministerio de Salud Pública y Bienestar Social (MSPBS)',
'url' => null,
'accessed' => null],
['title' => 'Antenatal care (NG201)',
'publisher' => 'National Institute for Health and Care Excellence (NICE)',
'url' => null,
'accessed' => null],
['title' => 'Ley 7383/2024 — permisos para controles prenatales (nota oficial del MTESS)', 'publisher' => 'Ministerio de Trabajo, Empleo y Seguridad Social (MTESS)', 'url' => 'https://www.mtess.gov.py/?p=30138', 'accessed' => '2026-09-20']]],
3 => ['title' => 'Tercer trimestre de embarazo',
'seoTitle' => 'Tercer trimestre: controles y preparación',
'metaDescription' => 'Prepará el tercer trimestre de embarazo: movimientos del bebé, controles finales, señales de parto y organización del nacimiento y la licencia laboral.',
'lead' => 'En el tercer trimestre el bebé gana peso y sus pulmones y cerebro siguen madurando. Podés notar más presión en la pelvis, acidez y dificultad para encontrar una postura cómoda. Los movimientos deben seguir presentes, aunque cambie cómo los sentís. Los controles revisan tu salud, el crecimiento y la preparación para el nacimiento. Acá se agrupan las semanas 28 a 42 de Mi Bebé; la fecha probable de parto es una referencia, y el equipo define el seguimiento si la superás.',
'timeline' => [['week' => 28,
'what' => 'Movimientos y control: aprendé a reconocer la actividad habitual de tu bebé. Si disminuye claramente o dejás de sentirlo, buscá atención inmediata, sin esperar al día siguiente. En la consulta revisan presión, crecimiento y resultados de estudios anteriores.'],
['week' => 30,
'what' => 'Vacunas pendientes: llevá el registro para que el equipo confirme qué corresponde completar durante el embarazo según tus antecedentes y el PAI. Anotá las aplicaciones realizadas para que la información acompañe tu atención al nacimiento.'],
['week' => 32,
'what' => 'Preparación del parto: conversá sobre dónde te van a atender, cómo llegar y a quién llamar cuando empiece. Preguntá por acompañamiento y opciones para aliviar el dolor disponibles en tu servicio. Organizá el traslado también para una urgencia.'],
['week' => 35,
'what' => 'Estudios del final: preguntá si te corresponde la muestra para estreptococo del grupo B y en qué fecha tomarla. Busca una bacteria que puede estar presente sin molestias; un resultado positivo permite planificar prevención durante el parto y no significa por sí solo que necesites cesárea.'],
['week' => 36,
'what' => 'Bolso y seguimiento: reuní tu carné, informes y estudios, y revisá la posición del bebé con tu equipo. La [semana 36](/semana/36/) te ayuda a preparar preguntas sobre presentación y comienzo del parto.'],
['week' => 38,
'what' => 'Licencia: la Ley 5508/2015 contempla una licencia de maternidad general de 18 semanas. Confirmá las fechas y los requisitos de tu caso con el empleador y, si corresponde, IPS. La licencia laboral no equivale a una indicación de reposo en cama. Revisá la guía de [licencia de maternidad](/derechos/licencia-de-maternidad/).'],
['week' => 40,
'what' => 'Cerca de la fecha probable: dejá acordado cuándo volver y qué hacer si no empieza el parto. Si hay pérdida de líquido, sangrado o menos movimientos, buscá atención inmediata aunque todavía no tengas contracciones regulares.'],
['week' => 42,
'what' => 'Seguimiento después de la fecha probable: esta tarjeta corresponde a 41 semanas completas más los días. Si llegaste a esta etapa sin un plan de atención y nacimiento, contactá hoy a tu equipo. Conversá sobre la inducción indicada para tu situación; no pruebes métodos caseros para provocar el parto.']],
'faq' => [['q' => '¿El bebé se mueve menos porque ya no tiene espacio?',
'a' => 'Puede cambiar el tipo de movimiento, pero una disminución clara no debe explicarse solamente por la falta de espacio. Buscá atención inmediata si se mueve menos de lo habitual o no lo sentís; no esperes al próximo control.'],
['q' => '¿Cómo distingo las contracciones del parto?',
'a' => 'Las del trabajo de parto suelen hacerse más regulares, intensas y cercanas. La evaluación confirma qué está ocurriendo. Seguí el plan de consulta acordado; si aparecen contracciones repetidas antes de las 37 semanas completas, pérdida de líquido o sangrado, buscá atención pronta. Revisá también las [señales de alarma](/salud/senales-de-alarma/).'],
['q' => '¿Qué pasa si llega la fecha probable y no nace?',
'a' => 'Esa fecha es una estimación. Necesitás un plan de controles y una conversación sobre cuándo conviene inducir el parto según tu edad gestacional y tu situación. La [semana 41](/semana/41/) explica el seguimiento; un control tranquilizador no reemplaza la consulta si después aparecen síntomas.'],
['q' => '¿Las semanas de las tarjetas son semanas completas?',
'a' => 'No: muestran la semana que está transcurriendo. Por ejemplo, la tarjeta 38 corresponde a 37 semanas completas y entre cero y seis días. Para decidir estudios o el nacimiento, usá las semanas y días anotados por tu equipo en el carné.']],
'sources' => [['title' => 'Recomendaciones de la OMS sobre atención prenatal para una experiencia positiva del embarazo',
'publisher' => 'Organización Mundial de la Salud (OMS)',
'url' => null,
'accessed' => null],
['title' => 'Orientaciones vigentes sobre control prenatal y vacunación durante el embarazo',
'publisher' => 'Ministerio de Salud Pública y Bienestar Social (MSPBS)',
'url' => null,
'accessed' => null],
['title' => 'WHO recommendations on induction of labour, at or beyond term',
'publisher' => 'Organización Mundial de la Salud (OMS)',
'url' => null,
'accessed' => null],
['title' => 'Ley 5508/2015 — promoción, protección de la maternidad y apoyo a la lactancia materna', 'publisher' => 'Biblioteca y Archivo Central del Congreso Nacional (BACN)', 'url' => 'https://www.bacn.gov.py/leyes-paraguayas/4428/promocion-proteccion-de-la-maternidad-y-apoyo-a-la-lactancia-materna', 'accessed' => '2026-09-20']]]
];
foreach ($_trimestres as $_trimestre => &$_record) {
    $_record['weeks'] = array_values(array_filter(range(1, 42), static fn(int $_n): bool => week_trimester($_n) === $_trimestre));
    $_record['reviewedBy'] = null;
    $_record['updated'] = '2026-09-20';
}
unset($_trimestre, $_record);
return $_trimestres;
