<?php
/**
 * Growth plan item 1 — "¿Puedo comer…?" pages, generated from the app's seed.
 *
 *     php tools/import-food.php [path/to/embarazo.2.1] [--preview-unreviewed]
 *
 * Reads <app>/lib/seed/food.json (default: ../embarazo.2.1 next to this repo) and writes
 * content/comer.php plus the route files under alimentacion/puedo-comer/. Name, verdict,
 * reason, detail and source are copied VERBATIM: the same fact must never be retyped in two
 * repos (growth plan rules).
 *
 * The app's review gate applies here too (app DECISIONS.md, PR-19): a food verdict renders
 * only when its seed record carries `reviewedBy`. Unreviewed entries are imported but not
 * published; with none reviewed there is no hub and no page. A food gets its own page only
 * when it is reviewed AND has a `detail` text; the one-line entries live on the hub only.
 *
 * --preview-unreviewed publishes every entry, for a LOCAL render check only. It marks the
 * file 'preview' => true and verify.sh fails while that mark is committed.
 */
declare(strict_types=1);

$root = dirname(__DIR__);
$args = array_slice($argv, 1);
$preview = in_array('--preview-unreviewed', $args, true);
$paths = array_values(array_filter($args, static fn(string $a): bool => !str_starts_with($a, '--')));
$app = rtrim($paths[0] ?? dirname($root) . '/embarazo.2.1', '/');
$seedFile = $app . '/lib/seed/food.json';
if (!is_file($seedFile)) {
    fwrite(STDERR, "No encuentro {$seedFile}. Pasá la ruta del repo de la app como primer argumento.\n");
    exit(1);
}
$seed = json_decode((string) file_get_contents($seedFile), true, 512, JSON_THROW_ON_ERROR);

$verdicts = ['safe', 'precaucion', 'evitar'];
$foods = [];
foreach ($seed as $i => $entry) {
    foreach (['id', 'name', 'verdict', 'reason', 'source'] as $key) {
        if (!is_string($entry[$key] ?? null) || trim($entry[$key]) === '') {
            fwrite(STDERR, "food.json[{$i}]: falta {$key}\n");
            exit(1);
        }
    }
    if (!in_array($entry['verdict'], $verdicts, true)) {
        fwrite(STDERR, "food.json[{$i}]: veredicto desconocido {$entry['verdict']}\n");
        exit(1);
    }
    $slug = preg_replace('/^food-/', '', $entry['id']);
    if (!preg_match('/\A[a-z0-9]+(?:-[a-z0-9]+)*\z/', $slug)) {
        fwrite(STDERR, "food.json[{$i}]: id no sirve como slug: {$entry['id']}\n");
        exit(1);
    }
    $reviewedBy = is_string($entry['reviewedBy'] ?? null) && trim($entry['reviewedBy']) !== '' ? trim($entry['reviewedBy']) : null;
    $detail = is_string($entry['detail'] ?? null) && trim($entry['detail']) !== '' ? $entry['detail'] : null;
    $published = $reviewedBy !== null || $preview;
    $foods[$slug] = [
        'name' => $entry['name'],
        'synonyms' => array_values(array_filter($entry['synonyms'] ?? [], 'is_string')),
        'verdict' => $entry['verdict'],
        'reason' => $entry['reason'],
        'detail' => $detail,
        'source' => $entry['source'],
        'reviewedBy' => $reviewedBy,
        'published' => $published,
        'page' => $published && $detail !== null,
    ];
}
uksort($foods, static fn(string $a, string $b): int => strcoll($foods[$a]['name'], $foods[$b]['name']) ?: strcmp($a, $b));

$out = "<?php\n/**\n * GENERATED by tools/import-food.php from the app's lib/seed/food.json. Do not edit by hand:\n"
    . " * fix the text in the app seed and re-run the import.\n"
    . " * updated: date of the import. foods: slug => {name,synonyms[],verdict:safe|precaucion|evitar,reason,detail:?string,source,\n"
    . " * reviewedBy:?string,published:bool (reviewed),page:bool (published AND has detail)}.\n */\n"
    . "declare(strict_types=1);\n\nreturn " . var_export(['preview' => $preview, 'updated' => date('Y-m-d'), 'foods' => $foods], true) . ";\n";
file_put_contents($root . '/content/comer.php', $out);

// Route files: exactly what deploy/routes.php expects, and nothing stale.
$base = $root . '/alimentacion/puedo-comer';
$wanted = [];
$anyPublished = (bool) array_filter($foods, static fn(array $f): bool => $f['published']);
if ($anyPublished) {
    $wanted[$base . '/index.php'] = "<?php\n\$slug = NULL;\nrequire __DIR__ . '/../../templates/food.php';\n";
}
foreach ($foods as $slug => $food) {
    if ($food['page']) {
        $wanted[$base . '/' . $slug . '/index.php'] = "<?php\n\$slug = " . var_export($slug, true) . ";\nrequire __DIR__ . '/../../../templates/food.php';\n";
    }
}
foreach (glob($base . '/*/index.php') ?: [] as $file) {
    if (!isset($wanted[$file])) { unlink($file); @rmdir(dirname($file)); }
}
if (!$anyPublished && is_file($base . '/index.php')) { unlink($base . '/index.php'); @rmdir($base); }
foreach ($wanted as $file => $code) {
    if (!is_dir(dirname($file))) { mkdir(dirname($file), 0755, true); }
    file_put_contents($file, $code);
}

$published = count(array_filter($foods, static fn(array $f): bool => $f['published']));
$pages = count(array_filter($foods, static fn(array $f): bool => $f['page']));
echo "comer: " . count($foods) . " alimentos, {$published} publicados (revisados), {$pages} con página propia"
    . ($preview ? " — VISTA PREVIA: no commitear" : '') . "\n";
