<?php
/**
 * Growth plan item 2 — baby-name pages, generated from the app's seed.
 *
 *     php tools/import-names.php [path/to/embarazo.2.1]
 *
 * Reads <app>/lib/seed/names.json (default: ../embarazo.2.1 next to this repo) and writes
 * content/nombres.php plus the route files under nombres/. Name, origin, gender and meaning
 * are copied VERBATIM (the same fact is never retyped in two repos). The app's placeholder
 * gate applies here too: an entry containing "placeholder" is not imported.
 *
 * Pages: the /nombres/ hub and one page per origin. A gender page (/nombres/<origin>/<gender>/)
 * exists only when that combination has at least MIN_GENDER_PAGE names: below that it would be
 * a strict subset of its origin page, i.e. a near-duplicate (AGENTS.md). Never one page per name.
 */
declare(strict_types=1);

const MIN_GENDER_PAGE = 15;
const ORIGIN_SLUGS = ['guarani' => 'guaranies', 'espanol' => 'espanoles', 'biblico' => 'biblicos'];
const GENDER_SLUGS = ['f' => 'nena', 'm' => 'varon', 'u' => 'para-cualquiera'];

$root = dirname(__DIR__);
$app = rtrim($argv[1] ?? dirname($root) . '/embarazo.2.1', '/');
$seedFile = $app . '/lib/seed/names.json';
if (!is_file($seedFile)) {
    fwrite(STDERR, "No encuentro {$seedFile}. Pasá la ruta del repo de la app como primer argumento.\n");
    exit(1);
}
$seed = json_decode((string) file_get_contents($seedFile), true, 512, JSON_THROW_ON_ERROR);

$names = [];
foreach ($seed as $i => $entry) {
    foreach (['name', 'origin', 'gender', 'meaning'] as $key) {
        if (!is_string($entry[$key] ?? null) || trim($entry[$key]) === '') {
            fwrite(STDERR, "names.json[{$i}]: falta {$key}\n");
            exit(1);
        }
    }
    if (!isset(ORIGIN_SLUGS[$entry['origin']]) || !isset(GENDER_SLUGS[$entry['gender']])) {
        fwrite(STDERR, "names.json[{$i}]: origen o género desconocido\n");
        exit(1);
    }
    if (str_contains(strtolower(json_encode($entry, JSON_UNESCAPED_UNICODE)), 'placeholder')) { continue; }
    $names[] = ['name' => $entry['name'], 'origin' => $entry['origin'], 'gender' => $entry['gender'], 'meaning' => $entry['meaning']];
}
usort($names, static fn(array $a, array $b): int => strcoll($a['name'], $b['name']));

$genderPages = [];
foreach (ORIGIN_SLUGS as $origin => $_) {
    foreach (GENDER_SLUGS as $gender => $_g) {
        $count = count(array_filter($names, static fn(array $n): bool => $n['origin'] === $origin && $n['gender'] === $gender));
        if ($count >= MIN_GENDER_PAGE) { $genderPages[] = [$origin, $gender]; }
    }
}

$out = "<?php\n/**\n * GENERATED by tools/import-names.php from the app's lib/seed/names.json. Do not edit by hand:\n"
    . " * fix the text in the app seed and re-run the import.\n"
    . " * updated: import date; originSlugs/genderSlugs: code => URL segment; names: [{name,origin,gender,meaning}]\n"
    . " * sorted A-Z; genderPages: [[origin, gender]] with their own page (>= " . MIN_GENDER_PAGE . " names).\n */\n"
    . "declare(strict_types=1);\n\nreturn " . var_export(['updated' => date('Y-m-d'), 'originSlugs' => ORIGIN_SLUGS,
        'genderSlugs' => GENDER_SLUGS, 'names' => $names, 'genderPages' => $genderPages], true) . ";\n";
file_put_contents($root . '/content/nombres.php', $out);

$wanted = [$root . '/nombres/index.php' => "<?php\n\$origin = NULL; \$gender = NULL;\nrequire __DIR__ . '/../templates/names.php';\n"];
foreach (ORIGIN_SLUGS as $origin => $slug) {
    $wanted[$root . '/nombres/' . $slug . '/index.php'] = "<?php\n\$origin = '{$origin}'; \$gender = NULL;\nrequire __DIR__ . '/../../templates/names.php';\n";
}
foreach ($genderPages as [$origin, $gender]) {
    $wanted[$root . '/nombres/' . ORIGIN_SLUGS[$origin] . '/' . GENDER_SLUGS[$gender] . '/index.php']
        = "<?php\n\$origin = '{$origin}'; \$gender = '{$gender}';\nrequire __DIR__ . '/../../../templates/names.php';\n";
}
foreach (glob($root . '/nombres/*/*/index.php') ?: [] as $file) {
    if (!isset($wanted[$file])) { unlink($file); @rmdir(dirname($file)); }
}
foreach ($wanted as $file => $code) {
    if (!is_dir(dirname($file))) { mkdir(dirname($file), 0755, true); }
    file_put_contents($file, $code);
}
echo 'nombres: ' . count($names) . ' nombres, ' . count(ORIGIN_SLUGS) . ' páginas por origen, ' . count($genderPages) . " páginas por género\n";
